// A known-good inclusion proof generated by `ballast-inclusion prove` over a
// demo 3-customer book, for the holder page to work out-of-the-box. The holder
// (account 0xB2…, balance 300 USDC) proves membership against SAMPLE_ROOT.
import type { InclusionProof } from "./sumtree.ts";

export const SAMPLE_ROOT =
  "5124e0e67526d47af1f033713967b4538d5ad2a70742d6d67a749bc31ace3fcd";

const b2 = new Array(32).fill(178);
const salt22 = new Array(32).fill(34);

export const SAMPLE_PROOF: InclusionProof = {
  leaf: { account: b2, balance: 3000000000, salt: salt22 },
  path: [
    {
      sibling_hash: [
        85, 246, 69, 133, 208, 188, 86, 77, 185, 75, 208, 92, 234, 4, 2, 99, 93,
        85, 14, 211, 207, 79, 207, 23, 156, 237, 180, 218, 74, 200, 162, 221,
      ],
      sibling_sum: 5000000000,
      is_left: false,
    },
    {
      sibling_hash: [
        251, 125, 242, 242, 251, 206, 124, 53, 176, 200, 104, 43, 34, 236, 95,
        21, 29, 90, 122, 55, 162, 51, 222, 116, 80, 165, 48, 153, 82, 132, 70,
        11,
      ],
      sibling_sum: 1000000000,
      is_left: true,
    },
  ],
};
